refactor: simplify the check step process

diff --git a/.github/workflows/3-copilot-edits.yml b/.github/workflows/3-copilot-edits.yml
--- a/.github/workflows/3-copilot-edits.yml
+++ b/.github/workflows/3-copilot-edits.yml
@@ -34,86 +34,69 @@ jobs:
       - name: Get response templates
         uses: actions/checkout@v4
         with:
-          repository: skills/response-templates
-          path: skills-response-templates
+          repository: skills/exercise-toolkit
+          path: exercise-toolkit
+          ref: step-results-table
 
       - name: Update comment - checking work
         run: |
           gh issue comment "$ISSUE_URL" \
-            --body-file skills-response-templates/step-feedback/checking-work.md \
+            --body-file exercise-toolkit/mardkown-templates/step-feedback/checking-work.md \
             --edit-last
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
       # START: Check practical exercise
 
-      - name: Check participant info on activity cards
-        id: check-user-work
+      - name: Check for participant info in app.js
+        id: check-app-js
+        continue-on-error: true
         run: |
-          # Checks to perform
-            checks='{
-              "app_js": {
-                "name": "app.js",
-                "passed": true,
-                "message": ""
-              },
-              "styles_css": {
-                "name": "styles.css",
-                "passed": true,
-                "message": ""
-              }
-            }'
-
-          # Check for participants info in app.js
           file="src/static/app.js"
           keyphrase='participant'
           minimum_occurences=3
           found_occurences=$(grep -o "$keyphrase" "$file" | wc -l)
           if [ "$found_occurences" -lt "$minimum_occurences" ]; then
-            checks=$(echo $checks | jq '.app_js.passed = false')
-            checks=$(echo $checks | jq '.app_js.message = "Please use Copilot to update the web application activity cards to show participant info."')
+            echo "::error::Please use Copilot to update the web application activity cards to show participant info."
+            exit 1
           fi
 
-          # Check for participants info in styles.css
+      - name: Check for participant info in styles.css
+        id: check-styles
+        continue-on-error: true
+        run: |
           file="src/static/styles.css"
           keyphrase='participant'
           minimum_occurences=1
+
           found_occurences=$(grep -o "$keyphrase" "$file" | wc -l)
           if [ "$found_occurences" -lt "$minimum_occurences" ]; then
-            checks=$(echo $checks | jq '.styles_css.passed = false')
-            checks=$(echo $checks | jq '.styles_css.message = "Please use Copilot to update the web application styling to support participant info."')
+            echo "::error::Please use Copilot to update the web application styling to support participant info."
+            exit 1
           fi
 
-          # Verify all checks passed
-          passed=$(echo $checks | jq '. | all(.passed?)')
-
-          # Flatten to an array for returning. Allows iteration during rendering.
-          results=$(echo $checks | jq 'to_entries | map({name: .key} + .value)')
-
-          # Save pass status to output
-          echo "passed=$passed" >> $GITHUB_OUTPUT
-
-          # Save results to output
-          echo 'results<<EOF' >> $GITHUB_OUTPUT
-          echo $results >> $GITHUB_OUTPUT
-          echo 'EOF' >> $GITHUB_OUTPUT
-        env:
-          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      # END: Check practical exercise
 
       - name: Build message - step results
         id: build-message-step-results
         uses: skills/action-text-variables@v1
         with:
-          template-file: skills-response-templates/step-feedback/step-results.md
-          template-vars: '{
-            "step_number": 3,
-            "passed": ${{ steps.check-user-work.outputs.passed }},
-            "results_table": ${{ steps.check-user-work.outputs.results }},
-            "tips": [
-            "Copilot is becoming more capable everyday. Make sure to always be experimenting!",
-            "Try testing what Copilot can do. Something like: Add a dark mode toggle in the top right."
-            ]
-            }'
+          template-file: exercise-toolkit/mardkown-templates/step-feedback/step-results-table.md
+          template-vars: >
+            {
+              "step_number": 3,
+              "passed": ${{ !contains(steps.*.outcome, 'failure') }},
+              "results_table": [
+                {
+                  "check": "Check `app.js` for participant info",
+                  "result": ${{ steps.check-app-js.outcome == 'success' }}
+                },
+                {
+                  "check": "Participant styling updated in `styles.css`",
+                  "result": ${{ steps.check-styles.outcome == 'success' }}
+                }
+              ]
+            }
 
       - name: Create comment - step results
         run: |
@@ -124,17 +107,11 @@ jobs:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           COMMENT_BODY: ${{ steps.build-message-step-results.outputs.updated-text }}
 
-      - name: Fail job if not all checks passed
-        if: steps.check-user-work.outputs.passed == 'false'
-        run: exit 1
-
-      # END: Check practical exercise
-
       - name: Build message - step finished
         id: build-message-step-finish
         uses: skills/action-text-variables@v1
         with:
-          template-file: skills-response-templates/step-feedback/step-finished-prepare-next-step.md
+          template-file: exercise-toolkit/markdown-templates/step-feedback/step-finished-prepare-next-step.md
           template-vars: |
             next_step_number=4
 
